<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product List</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100">
    @include('navbar')
    <div class="min-h-screen">
        <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
            <div class="px-4 py-6 sm:px-0">
                <div class="bg-white rounded-lg shadow">
                    <div class="px-4 py-5 border-b border-gray-200 sm:px-6">
                        <h2 class="text-xl font-bold text-gray-900">Product List</h2>
                        <p class="mt-1 text-sm text-gray-500">A complete list of all available products</p>
                    </div>
                    
                    <div class="overflow-x-auto">
                        <table class="min-w-full divide-y divide-gray-200">
                            <thead class="bg-gray-50">
                                <tr>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Product ID</th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Price</th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Stock</th>
                                </tr>
                            </thead>
                            <tbody class="bg-white divide-y divide-gray-200">
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">1</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Apple iPhone 14</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱55,990</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">2</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Samsung Galaxy S23</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱49,990</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">3</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">MacBook Pro 16"</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱139,990</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">15</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">4</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">HP Pavilion Laptop</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱44,990</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">5</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Dell XPS 13</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱61,990</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">20</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">6</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Logitech MX Master 3</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱5,590</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">7</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Razer BlackWidow Keyboard</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱7,290</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">35</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">8</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">JBL Flip 6 Speaker</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱5,590</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">9</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Sony WH-1000XM5</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱19,590</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">45</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">10</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Amazon Echo Dot</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱2,790</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">60</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">11</td><td class="px-6 py-4 text-sm font-medium text-gray-900">Coca-Cola 1L Bottle</td><td class="px-6 py-4 text-sm text-gray-500">₱65</td><td class="px-6 py-4 text-sm text-gray-500">100</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">12</td><td class="px-6 py-4 text-sm font-medium text-gray-900">Lay's Classic Chips</td><td class="px-6 py-4 text-sm text-gray-500">₱99</td><td class="px-6 py-4 text-sm text-gray-500">75</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">13</td><td class="px-6 py-4 text-sm font-medium text-gray-900">Oreo Cookies</td><td class="px-6 py-4 text-sm text-gray-500">₱95</td><td class="px-6 py-4 text-sm text-gray-500">90</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">14</td><td class="px-6 py-4 text-sm font-medium text-gray-900">Kellogg's Corn Flakes</td><td class="px-6 py-4 text-sm text-gray-500">₱199</td><td class="px-6 py-4 text-sm text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">15</td><td class="px-6 py-4 text-sm font-medium text-gray-900">Nutella 350g</td><td class="px-6 py-4 text-sm text-gray-500">₱299</td><td class="px-6 py-4 text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">16</td><td class="px-6 py-4 text-sm font-medium text-gray-900">HP Printer Ink Cartridge</td><td class="px-6 py-4 text-sm text-gray-500">₱1,890</td><td class="px-6 py-4 text-sm text-gray-500">30</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">17</td><td class="px-6 py-4 text-sm font-medium text-gray-900">Stapler with 1000 Staples</td><td class="px-6 py-4 text-sm text-gray-500">₱399</td><td class="px-6 py-4 text-sm text-gray-500">45</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">18</td><td class="px-6 py-4 text-sm font-medium text-gray-900">Pack of A4 Printing Paper</td><td class="px-6 py-4 text-sm text-gray-500">₱299</td><td class="px-6 py-4 text-sm text-gray-500">60</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">19</td><td class="px-6 py-4 text-sm font-medium text-gray-900">Pilot G2 Gel Pens (5-pack)</td><td class="px-6 py-4 text-sm text-gray-500">₱499</td><td class="px-6 py-4 text-sm text-gray-500">70</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">20</td><td class="px-6 py-4 text-sm font-medium text-gray-900">3M Post-it Notes</td><td class="px-6 py-4 text-sm text-gray-500">₱179</td><td class="px-6 py-4 text-sm text-gray-500">85</td></tr>

                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">21</td><td class="px-6 py-4 text-sm font-medium text-gray-900">Dyson V11 Vacuum Cleaner</td><td class="px-6 py-4 text-sm text-gray-500">₱33,990</td><td class="px-6 py-4 text-sm text-gray-500">10</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">22</td><td class="px-6 py-4 text-sm font-medium text-gray-900">Philips Air Fryer</td><td class="px-6 py-4 text-sm text-gray-500">₱8,490</td><td class="px-6 py-4 text-sm text-gray-500">15</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">23</td><td class="px-6 py-4 text-sm font-medium text-gray-900">Instant Pot 7-in-1</td><td class="px-6 py-4 text-sm text-gray-500">₱5,590</td><td class="px-6 py-4 text-sm text-gray-500">20</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">24</td><td class="px-6 py-4 text-sm font-medium text-gray-900">LG 65" OLED TV</td><td class="px-6 py-4 text-sm text-gray-500">₱119,990</td><td class="px-6 py-4 text-sm text-gray-500">5</td></tr>



                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">24</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">LG 65" OLED TV</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱119,990</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">5</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Whirlpool Refrigerator</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱66,990</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">8</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">26</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Nike Air Max Shoes</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱5,995</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">27</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Levi's 501 Jeans</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱2,995</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">28</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Uniqlo T-Shirt</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱590</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">100</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">29</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Adidas Running Shorts</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱1,495</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">45</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">H&M Dress</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱1,290</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">35</td></tr>
                                <!-- Beauty Products -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">31</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">MAC Lipstick</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱1,200</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">32</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">L'Oreal Face Cream</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱899</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">33</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Dove Body Wash</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱199</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">80</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">34</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Nivea Deodorant</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱129</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">100</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">35</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Head & Shoulders Shampoo</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱249</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">75</td></tr>
                                <!-- Sports Equipment -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">36</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Basketball</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">37</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Yoga Mat</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱799</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">38</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Dumbbells Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱2,499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">39</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Tennis Racket</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱1,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">20</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Swimming Goggles</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱399</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>
                                <!-- Books and Stationery -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">41</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Harry Potter Book Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱3,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">15</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">42</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Notebook Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱299</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">100</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">43</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Colored Pencils</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱199</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">80</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">44</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Art Sketchbook</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱399</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">45</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">45</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Dictionary</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱599</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td></tr>
                                <!-- Kitchen Items -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">46</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Non-stick Pan Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱2,499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">47</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Kitchen Knife Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱1,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">48</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Coffee Maker</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱3,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">20</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">49</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Food Container Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱799</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Blender</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱2,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td></tr>
                                <!-- Gaming -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">51</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">PlayStation 5</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱29,990</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">10</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">52</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Nintendo Switch</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱16,995</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">15</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">53</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Xbox Controller</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱3,495</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">54</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Gaming Headset</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱2,995</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">55</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Gaming Chair</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱8,995</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">20</td></tr>

                                <!-- Home Decor -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">56</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Wall Clock</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">57</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Photo Frame Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱799</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">58</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Table Lamp</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱1,299</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">35</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">59</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Throw Pillows</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">60</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">60</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Area Rug</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱2,499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td></tr>
                                <!-- Pet Supplies -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">61</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Dog Food (5kg)</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">62</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Cat Litter Box</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱799</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">63</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Pet Carrier</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱1,499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">64</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Pet Bed</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱899</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">35</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">65</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Pet Toys Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>

                                <!-- Garden Tools -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">66</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Garden Hose</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱799</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">67</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Plant Pots Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱599</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">68</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Gardening Tools Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱1,299</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">69</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Watering Can</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱299</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">70</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Garden Gloves</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱199</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">60</td></tr>

                                <!-- Automotive -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">71</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Car Battery</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱5,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">15</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">72</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Motor Oil</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">73</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Car Air Freshener</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱199</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">100</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">74</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Tire Gauge</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱299</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">75</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Car Wash Kit</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱899</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td></tr>

                                <!-- Musical Instruments -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">76</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Acoustic Guitar</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱7,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">10</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">77</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Digital Piano</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱24,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">5</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">78</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Drum Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱19,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">3</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">79</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Violin</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱8,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">8</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">80</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Guitar Strings Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱399</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">81</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Power Drill</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱3,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">20</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">82</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Toolbox Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱2,499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">83</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Measuring Tape</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱199</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">60</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">84</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Hammer</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱399</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">85</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Screwdriver Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱799</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">35</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">86</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Smart Watch</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱9,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">87</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Wireless Earbuds</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱4,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">88</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Power Bank</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱1,499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">89</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">USB Flash Drive</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">75</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">90</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Webcam</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱2,499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">91</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">LEGO Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱2,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">20</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">92</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Remote Control Car</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱1,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">93</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Doll Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">94</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Board Game</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱799</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">95</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Puzzle Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">96</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Treadmill</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱29,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">5</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">97</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Exercise Bike</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱15,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">8</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">98</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Jump Rope</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱299</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">100</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">99</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Resistance Bands Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱599</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">75</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">81</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Power Drill</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱3,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">20</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">82</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Toolbox Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱2,499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">83</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Measuring Tape</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱199</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">60</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">84</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Hammer</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱399</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">85</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Screwdriver Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱799</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">35</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">86</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Smart Watch</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱9,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">87</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Wireless Earbuds</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱4,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">88</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Power Bank</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱1,499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">89</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">USB Flash Drive</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">75</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">90</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Webcam</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱2,499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">91</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">LEGO Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱2,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">20</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">92</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Remote Control Car</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱1,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">25</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">93</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Doll Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">30</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">94</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Board Game</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱799</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">95</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Puzzle Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱499</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">96</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Treadmill</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱29,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">5</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">97</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Exercise Bike</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱15,999</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">8</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">98</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Jump Rope</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱299</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">100</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">99</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Resistance Bands Set</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱599</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">75</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">101</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Pancit Canton Pack</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱15</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">200</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">102</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">San Miguel Beer 6-pack</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱299</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">150</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">103</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Mang Tomas Sauce</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱45</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">100</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">104</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Dried Mangoes Pack</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱199</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">80</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">105</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Skyflakes Crackers</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱59</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">150</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">106</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Chicharon Pack</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱99</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">120</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">107</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Boy Bawang Cornick</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱29</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">200</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">108</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Piattos Chips</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱25</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">180</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">109</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Nova Multigrain Snacks</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱35</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">150</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">110</td><td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Nagaraya Nuts</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">₱45</td><td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">160</td></tr>
                                <!-- School Supplies -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">111</td><td class="px-6 py-4 font-medium text-gray-900">Scientific Calculator</td><td class="px-6 py-4 text-gray-500">₱999</td><td class="px-6 py-4 text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">112</td><td class="px-6 py-4 font-medium text-gray-900">School Backpack</td><td class="px-6 py-4 text-gray-500">₱1,299</td><td class="px-6 py-4 text-gray-500">35</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">113</td><td class="px-6 py-4 font-medium text-gray-900">Lunch Box Set</td><td class="px-6 py-4 text-gray-500">₱399</td><td class="px-6 py-4 text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">114</td><td class="px-6 py-4 font-medium text-gray-900">Water Bottle</td><td class="px-6 py-4 text-gray-500">₱299</td><td class="px-6 py-4 text-gray-500">75</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">115</td><td class="px-6 py-4 font-medium text-gray-900">Art Materials Set</td><td class="px-6 py-4 text-gray-500">₱599</td><td class="px-6 py-4 text-gray-500">45</td></tr>

                                <!-- Personal Care -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">116</td><td class="px-6 py-4 font-medium text-gray-900">Electric Toothbrush</td><td class="px-6 py-4 text-gray-500">₱2,499</td><td class="px-6 py-4 text-gray-500">30</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">117</td><td class="px-6 py-4 font-medium text-gray-900">Hair Dryer</td><td class="px-6 py-4 text-gray-500">₱1,499</td><td class="px-6 py-4 text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">118</td><td class="px-6 py-4 font-medium text-gray-900">Face Mask Pack</td><td class="px-6 py-4 text-gray-500">₱199</td><td class="px-6 py-4 text-gray-500">100</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">119</td><td class="px-6 py-4 font-medium text-gray-900">Nail Care Kit</td><td class="px-6 py-4 text-gray-500">₱399</td><td class="px-6 py-4 text-gray-500">55</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">120</td><td class="px-6 py-4 font-medium text-gray-900">Electric Razor</td><td class="px-6 py-4 text-gray-500">₱1,999</td><td class="px-6 py-4 text-gray-500">35</td></tr>

                                <!-- Local Accessories -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">121</td><td class="px-6 py-4 font-medium text-gray-900">Handwoven Bag</td><td class="px-6 py-4 text-gray-500">₱899</td><td class="px-6 py-4 text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">122</td><td class="px-6 py-4 font-medium text-gray-900">Bamboo Sunglasses</td><td class="px-6 py-4 text-gray-500">₱599</td><td class="px-6 py-4 text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">123</td><td class="px-6 py-4 font-medium text-gray-900">Shell Necklace</td><td class="px-6 py-4 text-gray-500">₱299</td><td class="px-6 py-4 text-gray-500">60</td></tr>

                                <!-- Home Storage -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">126</td><td class="px-6 py-4 font-medium text-gray-900">Storage Box Set</td><td class="px-6 py-4 text-gray-500">₱799</td><td class="px-6 py-4 text-gray-500">40</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">127</td><td class="px-6 py-4 font-medium text-gray-900">Clothes Hangers Pack</td><td class="px-6 py-4 text-gray-500">₱299</td><td class="px-6 py-4 text-gray-500">80</td></tr>

                                <!-- Smart Home -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">131</td><td class="px-6 py-4 font-medium text-gray-900">Smart Light Bulb</td><td class="px-6 py-4 text-gray-500">₱699</td><td class="px-6 py-4 text-gray-500">50</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">132</td><td class="px-6 py-4 font-medium text-gray-900">WiFi Security Camera</td><td class="px-6 py-4 text-gray-500">₱2,999</td><td class="px-6 py-4 text-gray-500">25</td></tr>

                                <!-- Mobile Accessories -->
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">136</td><td class="px-6 py-4 font-medium text-gray-900">Phone Case</td><td class="px-6 py-4 text-gray-500">₱499</td><td class="px-6 py-4 text-gray-500">100</td></tr>
                                <tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm text-gray-500">137</td><td class="px-6 py-4 font-medium text-gray-900">Screen Protector</td><td class="px-6 py-4 text-gray-500">₱299</td><td class="px-6 py-4 text-gray-500">150</td></tr>
                                <tr class="border-b"><td class="px-6 py-2">138</td><td class="px-6 py-2">Car Phone Mount</td><td class="px-6 py-2">₱599</td><td class="px-6 py-2">60</td></tr>
                                <tr class="border-b"><td class="px-6 py-2">139</td><td class="px-6 py-2">Selfie Stick</td><td class="px-6 py-2">₱399</td><td class="px-6 py-2">70</td></tr>
                                <tr class="border-b"><td class="px-6 py-2">140</td><td class="px-6 py-2">Phone Ring Holder</td><td class="px-6 py-2">₱199</td><td class="px-6 py-2">120</td></tr>
                                <tr class="border-b"><td class="px-6 py-2">141</td><td class="px-6 py-2">Travel Adapter</td><td class="px-6 py-2">₱799</td><td class="px-6 py-2">45</td></tr>
                                <tr class="border-b"><td class="px-6 py-2">142</td><td class="px-6 py-2">Neck Pillow</td><td class="px-6 py-2">₱399</td><td class="px-6 py-2">60</td></tr>
                                <tr class="border-b"><td class="px-6 py-2">143</td><td class="px-6 py-2">Luggage Tag Set</td><td class="px-6 py-2">₱199</td><td class="px-6 py-2">80</td></tr>
                                <tr class="border-b"><td class="px-6 py-2">144</td><td class="px-6 py-2">Travel Toiletry Kit</td><td class="px-6 py-2">₱599</td><td class="px-6 py-2">50</td></tr>
                                <tr class="border-b"><td class="px-6 py-2">145</td><td class="px-6 py-2">Passport Holder</td><td class="px-6 py-2">₱299</td><td class="px-6 py-2">70</td></tr>
                                <tr class="border-b"><td class="px-6 py-2">146</td><td class="px-6 py-2">Barong Tagalog</td><td class="px-6 py-2">₱2,999</td><td class="px-6 py-2">20</td></tr>
                                <tr class="border-b"><td class="px-6 py-2">147</td><td class="px-6 py-2">Banig Mat</td><td class="px-6 py-2">₱599</td><td class="px-6 py-2">40</td></tr>
                                <tr class="border-b"><td class="px-6 py-2">148</td><td class="px-6 py-2">Wooden Tinikling Set</td><td class="px-6 py-2">₱1,499</td><td class="px-6 py-2">15</td></tr>
                                <tr class="border-b"><td class="px-6 py-2">149</td><td class="px-6 py-2">Bamboo Wind Chimes</td><td class="px-6 py-2">₱399</td><td class="px-6 py-2">50</td></tr>
                                <tr class="border-b"><td class="px-6 py-2">150</td><td class="px-6 py-2">Traditional Fan</td><td class="px-6 py-2">₱299</td><td class="px-6 py-2">75</td></tr>
                            </tbody>
                        </table>
                  </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
<!-- Go Up Button -->
<button id="goUpBtn" class="hidden fixed bottom-5 right-5 bg-blue-500 text-white px-4 py-2 rounded-lg shadow-lg transition-opacity duration-300">
    ↑ Go Up
</button>

<script>
    const goUpBtn = document.getElementById("goUpBtn");
    window.onscroll = function () {
        if (document.documentElement.scrollTop > 200) {
            goUpBtn.classList.remove("hidden");
        } else {
            goUpBtn.classList.add("hidden");
        }
    };

    goUpBtn.onclick = function () {
        window.scrollTo({ top: 0, behavior: "smooth" });
    };
</script>




                                                                